## Importing Libraries

In [1]:
import pandas as pd

## Importing dataset

In [2]:
dataset = pd.read_csv(r'Job_Frauds.csv', encoding="ISO-8859-1")
print('Shape:', dataset.shape)
dataset.head(20)

Shape: (17880, 16)

,Job Title,Job Location,Department,Range_of_Salary,Profile,Job_Description,Requirements,Job_Benefits,Telecomunication,Comnpany_Logo,Type_of_Employment,Experience,Qualification,Type_of_Industry,Operations,Fraudulent
0,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,Other,Internship,NaN,NaN,Marketing,0
1,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,NaN,NaN,NaN,NaN,NaN,0
3,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI â Environmental Systems Re...,"EDUCATION:Â Bachelorâs or Masterâs in GIS,...",Our culture is anything but corporateâwe hav...,0,1,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
5,Accounting Clerk,"US, MD,",NaN,NaN,NaN,Job OverviewApex is an environmental consultin...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,0
6,Head of Content (m/f),"DE, BE, Berlin",ANDROIDPIT,20000-28000,"Founded in 2009, theÂ Fonpit AGÂ rose with its...",Your Responsibilities:Â Manage the English-spe...,Your Know-How:Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â ...,Your Benefits:Â Being part of a fast-growing c...,0,1,Full-time,Mid-Senior level,Master's Degree,Online Media,Management,0
7,Lead Guest Service Specialist,"US, CA, San Francisco",NaN,NaN,Airenvyâs mission is to provide lucrative ye...,Who is Airenvy?Hey there! We are seasoned entr...,"Experience with CRM software, live chat, and p...",Competitive Pay.Â You'll be able to eat steak ...,0,1,NaN,NaN,NaN,NaN,NaN,0
8,HP BSM SME,"US, FL, Pensacola",NaN,NaN,Solutions3 is a woman-owned small business who...,Implementation/Configuration/Testing/Training ...,MUST BE A US CITIZEN.An active TS/SCI clearanc...,NaN,0,1,Full-time,Associate,NaN,Information Technology and Services,NaN,0
9,Customer Service Associate - Part Time,"US, AZ, Phoenix",NaN,NaN,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,NaN,0,1,Part-time,Entry level,High School or equivalent,Financial Services,Customer Service,0
10,ASP.net Developer Job opportunity at United St...,"US, NJ, Jersey City",NaN,100000-120000,NaN,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,Position : #URL_86fd830a95a64e2b30ceed829e63fd...,Benefits - FullBonus Eligible - YesInterview T...,0,0,Full-time,Mid-Senior level,Bachelor's Degree,Information Technology and Services,Information Technology,0
11,Talent Sourcer (6 months fixed-term contract),"GB, LND, London",HR,NaN,Want to build a 21st century financial service...,TransferWise is the clever new way to move mon...,Weâre looking for someone who:Proven track r...,You will join one of Europeâs most hotly tip...,0,1,NaN,NaN,NaN,NaN,NaN,0
12,"Applications Developer, Digital","US, CT, Stamford",NaN,NaN,"Novitex Enterprise Solutions, formerly Pitney ...","The Applications Developer, Digital will devel...",Requirements:4 â 5 yearsâ experience in de...,NaN,0,1,Full-time,Associate,Bachelor's Degree,Management Consulting,Information Technology,0
13,Installers,"US, FL, Orlando",NaN,NaN,Growing event production company providing sta...,"Event Industry Installers Needed!! (Orlando, F...","Valid driver's license,Somewhat Clean driving ...",NaN,0,1,Full-time,Not Applicable,Unspecified,Events Services,Other,0
14,Account Executive - Sydney,"AU, NSW, Sydney",Sales,NaN,Adthena is the UKâs leading competitive inte...,Are you interested in a satisfying and financi...,Youâll need to be smart and passionate and h...,"In return we'll pay you well, give you some ow...",0,1,Full-time,Associate,Bachelor's Degree,Internet,Sales,0
15,VP of Sales - Vault Dragon,"SG, 01, Singapore",Sales,120000-150000,Jungle Ventures is the leading Singapore based...,About Vault DragonÂ Vault Dragon is Dropbox fo...,Key Superpowers3-5 years of high-pressure sale...,"Basic: SGD 120,000Equity negotiable for a rock...",0,1,Full-time,Executive,Bachelor's Degree,Facilities Services,Sales,0
16,Hands-On QA Leader,"IL, , Tel Aviv, Israel",R&D,NaN,At HoneyBook weâre re-imagining the events i...,We are looking for a Hands-On QA Leader for ou...,Previous experience in client &amp; server tes...,NaN,0,1,Full-time,Mid-Senior level,NaN,Internet,Engineering,0
17,Southend-on-Sea Traineeships Under NAS 16-18 Y...,"GB, SOS, Southend-on-Sea",NaN,NaN,Established on the principles that full time e...,Government funding is only available for 16-18...,16-18 year olds only due to government funding...,Career prospects.,0,1,NaN,NaN,NaN,NaN,NaN,0
18,Visual Designer,"US, NY, New York",NaN,NaN,Kettle is an independent digital agency based ...,Kettle is hiring a Visual Designer!Job Locatio...,NaN,NaN,0,1,NaN,NaN,NaN,NaN,NaN,0
19,Process Controls Engineer - DCS PLC MS Office ...,"US, PA, USA Northeast",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Process Controls Engineer is requi...,Must have 5 or more years of experience with D...,NaN,0,0,Full-time,NaN,NaN,NaN,NaN,0

### Data Type Check

In [3]:
dataset.info()

# all features seems to be in their correct data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job Title           17880 non-null  object
 1   Job Location        17534 non-null  object
 2   Department          6333 non-null   object
 3   Range_of_Salary     2868 non-null   object
 4   Profile             14572 non-null  object
 5   Job_Description     17879 non-null  object
 6   Requirements        15185 non-null  object
 7   Job_Benefits        10670 non-null  object
 8   Telecomunication    17880 non-null  int64
 9   Comnpany_Logo       17880 non-null  int64
 10  Type_of_Employment  14409 non-null  object
 11  Experience          10830 non-null  object
 12  Qualification       9775 non-null   object
 13  Type_of_Industry    12977 non-null  object
 14  Operations          11425 non-null  object
 15  Fraudulent          17880 non-null  int64
dtypes: int64(3), object(13)
memory usage: 2.2+ MB

### Checking for null values

In [4]:
dataset.isna().sum()

Job Title                 0
Job Location            346
Department            11547
Range_of_Salary       15012
Profile                3308
Job_Description           1
Requirements           2695
Job_Benefits           7210
Telecomunication          0
Comnpany_Logo             0
Type_of_Employment     3471
Experience             7050
Qualification          8105
Type_of_Industry       4903
Operations             6455
Fraudulent                0
dtype: int64